/**
 * WordPress dependencies
 */
// Stateless grammar parser (the JS twin of PHP `parse_blocks`); resolved
// from the framework at runtime (wp-block-serialization-default-parser).
// eslint-disable-next-line import/no-unresolved -- Provided at runtime as wp.blockSerializationDefaultParser.
import { parse as parseBlockGrammar } from '@wordpress/block-serialization-default-parser';

/*
 * The DE-RTC block-native client-update descriptor builder: the
 * client-side twin of the frozen merge core's
 * `wp_de_rtc_create_automerge_update_for_content_change()`.
 *
 * The descriptor is TAMPER EVIDENCE, not merge input: the server derives
 * the exact same update from the (base, proposed) pair and rejects the
 * proposal when the fingerprints disagree (`de_rtc_sync_meta_tampered`).
 * Merge outcomes are identical with or without it. Because a mismatch
 * REJECTS a legitimate save, every function here must byte-match its PHP
 * twin — the contract is enforced by PHP-generated fixture vectors
 * (tests/js/engines/de-rtc/test-vectors/, regenerated by
 * `tests/tools/generate-de-rtc-descriptor-vectors.php`). Do not change
 * behavior here without regenerating and re-running the vectors.
 *
 * Only fingerprinted fields need parity: operation types/paths/ordering,
 * sha256 content hashes, block names, `textSplice` (code-point counts +
 * insert-text hash), and `changedTextIndexes`. (`changeRange` is carried
 * for shape fidelity but is NOT fingerprinted server-side.)
 */

interface ParsedGrammarBlock {
	blockName: string | null;
	attrs: Record< string, unknown > | null;
	innerBlocks: ParsedGrammarBlock[];
	innerHTML: string;
	innerContent: Array< string | null >;
}

export interface DeRtcClientUpdate {
	format: 'native-automerge-blocks-v1';
	schema: 'de-rtc-automerge-v1';
	operations: Array< Record< string, unknown > >;
	stateVector: Record< string, number >;
	baseContentHash: string;
	proposedContentHash: string;
	baseBlockCount: number | null;
	proposedBlockCount: number | null;
}

/* -------------------------------------------------------------------- */
/* SHA-256 (sync — WebCrypto's digest is async and this path is not).   */
/* Standard FIPS 180-4 implementation over UTF-8 bytes.                 */
/* -------------------------------------------------------------------- */

/* eslint-disable no-bitwise -- FIPS 180-4 SHA-256 is bitwise math. */

// prettier-ignore
const SHA256_K = [
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

function sha256Hex( input: string ): string {
	const bytes = new TextEncoder().encode( input );
	const bitLength = bytes.length * 8;
	// Padded message: 0x80, zeros, 64-bit big-endian length.
	const paddedLength = ( ( ( bytes.length + 8 ) >> 6 ) + 1 ) << 6;
	const padded = new Uint8Array( paddedLength );
	padded.set( bytes );
	padded[ bytes.length ] = 0x80;
	const view = new DataView( padded.buffer );
	view.setUint32( paddedLength - 8, Math.floor( bitLength / 0x100000000 ) );
	view.setUint32( paddedLength - 4, bitLength >>> 0 );

	const state = [
		0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c,
		0x1f83d9ab, 0x5be0cd19,
	];
	const w = new Int32Array( 64 );

	for ( let offset = 0; offset < paddedLength; offset += 64 ) {
		for ( let i = 0; i < 16; i++ ) {
			w[ i ] = view.getInt32( offset + i * 4 );
		}
		for ( let i = 16; i < 64; i++ ) {
			const w15 = w[ i - 15 ];
			const w2 = w[ i - 2 ];
			const s0 =
				( ( w15 >>> 7 ) | ( w15 << 25 ) ) ^
				( ( w15 >>> 18 ) | ( w15 << 14 ) ) ^
				( w15 >>> 3 );
			const s1 =
				( ( w2 >>> 17 ) | ( w2 << 15 ) ) ^
				( ( w2 >>> 19 ) | ( w2 << 13 ) ) ^
				( w2 >>> 10 );
			w[ i ] = ( w[ i - 16 ] + s0 + w[ i - 7 ] + s1 ) | 0;
		}

		let [ a, b, c, d, e, f, g, h ] = state;
		for ( let i = 0; i < 64; i++ ) {
			const s1 =
				( ( e >>> 6 ) | ( e << 26 ) ) ^
				( ( e >>> 11 ) | ( e << 21 ) ) ^
				( ( e >>> 25 ) | ( e << 7 ) );
			const ch = ( e & f ) ^ ( ~e & g );
			const t1 = ( h + s1 + ch + SHA256_K[ i ] + w[ i ] ) | 0;
			const s0 =
				( ( a >>> 2 ) | ( a << 30 ) ) ^
				( ( a >>> 13 ) | ( a << 19 ) ) ^
				( ( a >>> 22 ) | ( a << 10 ) );
			const maj = ( a & b ) ^ ( a & c ) ^ ( b & c );
			const t2 = ( s0 + maj ) | 0;
			h = g;
			g = f;
			f = e;
			e = ( d + t1 ) | 0;
			d = c;
			c = b;
			b = a;
			a = ( t1 + t2 ) | 0;
		}
		state[ 0 ] = ( state[ 0 ] + a ) | 0;
		state[ 1 ] = ( state[ 1 ] + b ) | 0;
		state[ 2 ] = ( state[ 2 ] + c ) | 0;
		state[ 3 ] = ( state[ 3 ] + d ) | 0;
		state[ 4 ] = ( state[ 4 ] + e ) | 0;
		state[ 5 ] = ( state[ 5 ] + f ) | 0;
		state[ 6 ] = ( state[ 6 ] + g ) | 0;
		state[ 7 ] = ( state[ 7 ] + h ) | 0;
	}

	return state
		.map( ( word ) => ( word >>> 0 ).toString( 16 ).padStart( 8, '0' ) )
		.join( '' );
}
/* eslint-enable no-bitwise */

/* -------------------------------------------------------------------- */
/* Serializer twins: PHP serialize_block / serialize_block_attributes.  */
/* -------------------------------------------------------------------- */

/**
 * Twin of core PHP `serialize_block_attributes()` — identical to
 * `@wordpress/blocks`' serializeAttributes (the two are the established
 * cross-language save-format contract).
 *
 * @param attrs Block attributes.
 * @return Serialized attribute JSON.
 */
function serializeBlockAttributes( attrs: Record< string, unknown > ): string {
	return JSON.stringify( attrs )
		.replace( /--/g, '\\u002d\\u002d' )
		.replace( /</g, '\\u003c' )
		.replace( />/g, '\\u003e' )
		.replace( /&/g, '\\u0026' )
		.replace( /\\"/g, '\\u0022' );
}

/**
 * Twin of core PHP `serialize_block()` over the grammar parser's output.
 *
 * @param block Parsed grammar block.
 * @return Serialized block.
 */
function serializeGrammarBlock( block: ParsedGrammarBlock ): string {
	let content = '';
	let innerIndex = 0;
	for ( const chunk of block.innerContent ) {
		content +=
			'string' === typeof chunk
				? chunk
				: serializeGrammarBlock( block.innerBlocks[ innerIndex++ ] );
	}

	if ( null === block.blockName ) {
		return content;
	}

	const name = block.blockName.startsWith( 'core/' )
		? block.blockName.slice( 5 )
		: block.blockName;
	const attrs = block.attrs ?? {};
	const serializedAttrs =
		0 === Object.keys( attrs ).length
			? ''
			: serializeBlockAttributes( attrs ) + ' ';

	if ( '' === content ) {
		return `<!-- wp:${ name } ${ serializedAttrs }/-->`;
	}

	return `<!-- wp:${ name } ${ serializedAttrs }-->${ content }<!-- /wp:${ name } -->`;
}

/**
 * Twin of PHP `parse_blocks()` + serialize round trip.
 *
 * @param content Serialized content.
 * @return Parsed blocks and their re-serialization.
 */
function parseAndReserialize( content: string ): {
	blocks: ParsedGrammarBlock[];
	roundtrip: string;
} {
	const blocks = parseBlockGrammar( content ) as ParsedGrammarBlock[];
	let roundtrip = '';
	for ( const block of blocks ) {
		roundtrip += serializeGrammarBlock( block );
	}
	return { blocks, roundtrip };
}

/* -------------------------------------------------------------------- */
/* Canonicalization twins.                                              */
/* -------------------------------------------------------------------- */

/**
 * Twin of `wp_de_rtc_strip_core_block_namespace_from_serialized_comments`.
 *
 * @param content Serialized content.
 * @return Content with `wp:core/` delimiter spelling normalized.
 */
function stripCoreBlockNamespace( content: string ): string {
	return content.replace(
		/<!--\s*(\/?)wp:core\/([^\s>]+)([\s\S]*?)-->/g,
		'<!-- $1wp:$2$3-->'
	);
}

/**
 * Twin of `wp_de_rtc_canonicalize_post_content_core_block_names`.
 *
 * @param content Serialized content.
 * @return Canonical content when only implicit-core spelling differs.
 */
export function canonicalizeCoreBlockNames( content: string ): string {
	if ( -1 === content.toLowerCase().indexOf( 'wp:core/' ) ) {
		return content;
	}

	const { roundtrip } = parseAndReserialize( content );
	if ( roundtrip === content ) {
		return content;
	}
	if ( stripCoreBlockNamespace( content ) === roundtrip ) {
		return roundtrip;
	}
	return content;
}

/**
 * Twin of `wp_de_rtc_canonicalize_serialized_block_boundary_whitespace`.
 *
 * @param content Serialized content.
 * @return Content with block-boundary whitespace normalized.
 */
function canonicalizeBoundaryWhitespace( content: string ): string {
	return content
		.replace( /(<!--\s*wp:[\s\S]*?-->)\s+(?=<)/g, '$1' )
		.replace( /(?<=>)\s+(<!--\s*\/wp:[\s\S]*?-->)/g, '$1' )
		.replace( /(<!--\s*\/wp:[\s\S]*?-->)\s+(?=<!--\s*wp:)/g, '$1' );
}

/**
 * Twin of `wp_de_rtc_canonicalize_post_content_for_hash`.
 *
 * @param content Serialized content.
 * @return Canonicalized content for hash evidence.
 */
export function canonicalizeContentForHash( content: string ): string {
	return canonicalizeBoundaryWhitespace(
		canonicalizeCoreBlockNames( content )
	);
}

/**
 * Twin of `wp_de_rtc_hash_content`.
 *
 * @param content Serialized content.
 * @return SHA-256 content hash.
 */
export function hashDeRtcContent( content: string ): string {
	return sha256Hex( canonicalizeContentForHash( content ) );
}

/**
 * Twin of `wp_de_rtc_get_top_level_serialized_block_records`. Returns
 * null where PHP returns a WP_Error (freeform boundary, or a parse →
 * serialize round trip that changes bytes) — the caller falls back to
 * the whole-document `document.replace_unsupported` evidence.
 *
 * @param content Stripped post content.
 * @return Top-level serialized records, or null when unsafe.
 */
export function getTopLevelBlockRecords( content: string ): string[] | null {
	const canonical = canonicalizeContentForHash( content );
	const { blocks } = parseAndReserialize( canonical );
	const records: string[] = [];
	let roundtrip = '';

	for ( const block of blocks ) {
		const serialized = serializeGrammarBlock( block );
		roundtrip += serialized;

		if ( null === block.blockName ) {
			if ( '' !== serialized.trim() ) {
				return null; // Freeform boundary.
			}
			continue;
		}
		records.push( serialized );
	}

	if ( roundtrip !== canonical ) {
		return null; // Round trip changed bytes.
	}
	return records;
}

/**
 * Twin of `wp_de_rtc_get_serialized_block_record_name`.
 *
 * @param record Serialized block record.
 * @return Block name, or null when parsing is ambiguous.
 */
function getBlockRecordName( record: string ): string | null {
	const canonical = canonicalizeContentForHash( record );
	const { blocks } = parseAndReserialize( canonical );

	if (
		1 !== blocks.length ||
		! blocks[ 0 ].blockName ||
		serializeGrammarBlock( blocks[ 0 ] ) !== canonical
	) {
		return null;
	}
	return blocks[ 0 ].blockName;
}

/* -------------------------------------------------------------------- */
/* Text twins: code-point splits, UTF-16 lengths, change descriptors.   */
/* -------------------------------------------------------------------- */

/**
 * Twin of `wp_de_rtc_split_utf8_string` (Unicode code points).
 * @param text
 */
const splitCodePoints = ( text: string ): string[] => Array.from( text );

/**
 * Twin of `wp_de_rtc_get_automerge_content_change_descriptor`: single
 * change region by code-point prefix/suffix, measured in UTF-16 units.
 *
 * @param base Base text.
 * @param next Next text.
 * @return Change-range descriptor (client key shape).
 */
function getContentChangeRange( base: string, next: string ) {
	const baseChars = splitCodePoints( base );
	const nextChars = splitCodePoints( next );
	let prefix = 0;
	while (
		prefix < baseChars.length &&
		prefix < nextChars.length &&
		baseChars[ prefix ] === nextChars[ prefix ]
	) {
		prefix++;
	}
	let suffix = 0;
	while (
		suffix < baseChars.length - prefix &&
		suffix < nextChars.length - prefix &&
		baseChars[ baseChars.length - 1 - suffix ] ===
			nextChars[ nextChars.length - 1 - suffix ]
	) {
		suffix++;
	}

	const deletedText = baseChars
		.slice( prefix, baseChars.length - suffix )
		.join( '' );
	const insertText = nextChars
		.slice( prefix, nextChars.length - suffix )
		.join( '' );
	// UTF-16 code-unit lengths (JS string length IS the UTF-16 length).
	const index = baseChars.slice( 0, prefix ).join( '' ).length;
	const deleteLength = deletedText.length;
	const insertLength = insertText.length;

	return {
		start: index,
		end: index + deleteLength,
		deleteLength,
		insertLength,
		changed: deleteLength > 0 || '' !== insertText,
	};
}

/* -------------------------------------------------------------------- */
/* Rich-text twins.                                                     */
/* -------------------------------------------------------------------- */

interface RichTextModel {
	text: string;
	marks: Array< { type: string; start: number; end: number } >;
}

/**
 * Twin of `wp_de_rtc_get_paragraph_rich_text_block_parts`.
 *
 * @param block Serialized block record.
 * @return Open/html/close parts or null.
 */
function getParagraphParts(
	block: string
): { open: string; html: string; close: string } | null {
	const match =
		/^(<!--\s+wp:paragraph\b[\s\S]*?-->\s*<p\b[^>]*>)([\s\S]*?)(<\/p>\s*<!--\s+\/wp:paragraph\s+-->)$/i.exec(
			block
		);
	if ( ! match ) {
		return null;
	}
	return { open: match[ 1 ], html: match[ 2 ], close: match[ 3 ] };
}

/**
 * Twin of PHP `html_entity_decode( $t, ENT_QUOTES | ENT_HTML5, 'UTF-8' )`.
 *
 * PHP decodes ONLY semicolon-terminated references from the HTML5 table
 * (verified by vector `entity-no-semicolon`: a bare `&amp` stays
 * literal), while raw browser text parsing also legacy-decodes bare
 * named forms. So: extract each well-formed `&...;` candidate and decode
 * it in isolation via textarea RCDATA (the browser's HTML5 named table =
 * PHP's ENT_HTML5 table); a candidate the browser only PARTIALLY decodes
 * (e.g. `&ampx;` → `&x;`, still ending in `;`) is not a table entry and
 * stays literal, matching PHP.
 *
 * @param text Text token (no complete tags).
 * @return Decoded text.
 */
function decodeHtmlEntities( text: string ): string {
	if ( -1 === text.indexOf( '&' ) ) {
		return text;
	}
	return text.replace(
		/&(?:[a-zA-Z][a-zA-Z0-9]*|#[0-9]+|#[xX][0-9a-fA-F]+);/g,
		( candidate ) => {
			const textarea = document.createElement( 'textarea' );
			textarea.innerHTML = candidate;
			const decoded = textarea.value;
			if ( decoded === candidate ) {
				return candidate; // Unknown reference.
			}
			// A NAMED candidate whose decode still ends in ';' was only
			// partially matched (a numeric one always decodes whole —
			// `&#59;` legitimately IS ';').
			if ( '#' !== candidate[ 1 ] && decoded.endsWith( ';' ) ) {
				return candidate;
			}
			return decoded;
		}
	);
}

/**
 * Twin of `wp_de_rtc_pop_rich_text_active_mark`.
 *
 * @param activeMarks Active mark stack (mutated).
 * @param mark        Mark to pop.
 * @return Whether the mark was popped.
 */
function popActiveMark( activeMarks: string[], mark: string ): boolean {
	for ( let index = activeMarks.length - 1; index >= 0; index-- ) {
		if ( activeMarks[ index ] === mark ) {
			activeMarks.splice( index, 1 );
			return true;
		}
	}
	return false;
}

/**
 * Twin of `wp_de_rtc_coalesce_rich_text_marks`.
 *
 * @param marks Mark ranges.
 * @return Coalesced mark ranges.
 */
function coalesceMarks(
	marks: RichTextModel[ 'marks' ]
): RichTextModel[ 'marks' ] {
	const sorted = [ ...marks ].sort( ( a, b ) => {
		if ( a.type === b.type ) {
			if ( a.start === b.start ) {
				return a.end - b.end;
			}
			return a.start - b.start;
		}
		return a.type < b.type ? -1 : 1;
	} );

	const coalesced: RichTextModel[ 'marks' ] = [];
	for ( const mark of sorted ) {
		const last = coalesced[ coalesced.length - 1 ];
		if ( last && last.type === mark.type && last.end === mark.start ) {
			last.end = mark.end;
		} else {
			coalesced.push( { ...mark } );
		}
	}
	return coalesced;
}

/**
 * Twin of `wp_de_rtc_get_rich_text_format_model`.
 *
 * @param html Paragraph inner HTML.
 * @return Rich-text model or null for unsupported HTML.
 */
function getRichTextFormatModel( html: string ): RichTextModel | null {
	// preg_split with DELIM_CAPTURE | NO_EMPTY.
	const tokens = html.split( /(<[^>]+>)/ ).filter( ( t ) => '' !== t );

	let text = '';
	const marks: RichTextModel[ 'marks' ] = [];
	const activeMarks: string[] = [];
	let offset = 0;

	for ( const token of tokens ) {
		// PHP classifies on the first character alone: a stray unpaired
		// '<' makes the token a (never-matching) tag and the model null.
		if ( '<' === token[ 0 ] ) {
			const normalized = token.replace( /\s+/g, '' ).toLowerCase();

			if ( '<strong>' === normalized || '<b>' === normalized ) {
				activeMarks.push( 'strong' );
				continue;
			}
			if ( '</strong>' === normalized || '</b>' === normalized ) {
				if ( ! popActiveMark( activeMarks, 'strong' ) ) {
					return null;
				}
				continue;
			}
			if ( '<em>' === normalized || '<i>' === normalized ) {
				activeMarks.push( 'em' );
				continue;
			}
			if ( '</em>' === normalized || '</i>' === normalized ) {
				if ( ! popActiveMark( activeMarks, 'em' ) ) {
					return null;
				}
				continue;
			}
			return null;
		}

		const decoded = decodeHtmlEntities( token );
		for ( const char of splitCodePoints( decoded ) ) {
			text += char;
			for ( const mark of activeMarks ) {
				marks.push( { type: mark, start: offset, end: offset + 1 } );
			}
			offset++;
		}
	}

	if ( activeMarks.length > 0 ) {
		return null;
	}
	return { text, marks: coalesceMarks( marks ) };
}

/**
 * Twin of `wp_de_rtc_rich_text_has_mark_at`.
 *
 * @param model Rich-text model.
 * @param mark  Mark type.
 * @param index Character index.
 * @return Whether the mark covers the index.
 */
function hasMarkAt(
	model: RichTextModel,
	mark: string,
	index: number
): boolean {
	return model.marks.some(
		( range ) =>
			range.type === mark && range.start <= index && index < range.end
	);
}

/**
 * Twin of `wp_de_rtc_get_rich_text_changed_indexes`.
 *
 * @param base Base model.
 * @param next Next model.
 * @return Changed character indexes.
 */
function getChangedMarkIndexes(
	base: RichTextModel,
	next: RichTextModel
): number[] {
	const changed: number[] = [];
	const count = splitCodePoints( base.text ).length;

	for ( let index = 0; index < count; index++ ) {
		for ( const mark of [ 'strong', 'em' ] ) {
			if (
				hasMarkAt( base, mark, index ) !==
				hasMarkAt( next, mark, index )
			) {
				changed.push( index );
				break;
			}
		}
	}
	return changed;
}

/**
 * Twin of `wp_de_rtc_get_rich_text_text_splice` +
 * `wp_de_rtc_format_rich_text_text_splice_for_client` (client shape,
 * code-point units).
 *
 * @param baseText Base visible text.
 * @param nextText Next visible text.
 * @return Client-shaped text-splice evidence.
 */
function getTextSplice( baseText: string, nextText: string ) {
	if ( baseText === nextText ) {
		return {
			changed: false,
			start: 0,
			deleteCount: 0,
			insertText: '',
			insertCount: 0,
			end: 0,
			delta: 0,
		};
	}

	const baseChars = splitCodePoints( baseText );
	const nextChars = splitCodePoints( nextText );
	let prefix = 0;
	while (
		prefix < baseChars.length &&
		prefix < nextChars.length &&
		baseChars[ prefix ] === nextChars[ prefix ]
	) {
		prefix++;
	}
	let suffix = 0;
	while (
		suffix < baseChars.length - prefix &&
		suffix < nextChars.length - prefix &&
		baseChars[ baseChars.length - 1 - suffix ] ===
			nextChars[ nextChars.length - 1 - suffix ]
	) {
		suffix++;
	}

	const deleteCount = baseChars.length - prefix - suffix;
	const insertChars = nextChars.slice( prefix, nextChars.length - suffix );

	return {
		changed: true,
		start: prefix,
		deleteCount,
		insertText: insertChars.join( '' ),
		insertCount: insertChars.length,
		end: prefix + deleteCount,
		delta: insertChars.length - deleteCount,
	};
}

/* -------------------------------------------------------------------- */
/* Operation builders.                                                  */
/* -------------------------------------------------------------------- */

/**
 * Twin of `wp_de_rtc_get_automerge_block_native_rich_text_operation`.
 *
 * @param baseBlock Base serialized block.
 * @param nextBlock Proposed serialized block.
 * @param baseHash  Base block hash.
 * @param nextHash  Proposed block hash.
 * @param blockName Block name.
 * @param path      Top-level ordinal path.
 * @return Operation body or null.
 */
function getRichTextOperation(
	baseBlock: string,
	nextBlock: string,
	baseHash: string,
	nextHash: string,
	blockName: string,
	path: number[]
): Record< string, unknown > | null {
	const base = getParagraphParts( baseBlock );
	const next = getParagraphParts( nextBlock );
	if (
		! base ||
		! next ||
		base.open !== next.open ||
		base.close !== next.close
	) {
		return null;
	}

	const baseModel = getRichTextFormatModel( base.html );
	const nextModel = getRichTextFormatModel( next.html );
	if ( ! baseModel || ! nextModel ) {
		return null;
	}

	if ( baseModel.text !== nextModel.text ) {
		return {
			type: 'block.rich_text_content',
			automergePrimitive: 'Automerge.Text.splice',
			path,
			blockUid: 'top:' + baseHash,
			blockName,
			field: 'innerHTML',
			baseBlockHash: baseHash,
			proposedBlockHash: nextHash,
			textSplice: getTextSplice( baseModel.text, nextModel.text ),
			serializedBlock: nextBlock,
		};
	}

	return {
		type: 'block.rich_text_format',
		automergePrimitive: 'Automerge.Text.mark',
		path,
		blockUid: 'top:' + baseHash,
		blockName,
		field: 'innerHTML',
		baseBlockHash: baseHash,
		proposedBlockHash: nextHash,
		changedTextIndexes: getChangedMarkIndexes( baseModel, nextModel ),
		serializedBlock: nextBlock,
	};
}

/**
 * Twin of `wp_de_rtc_get_automerge_block_native_update_operation`.
 *
 * @param baseBlock Base serialized block.
 * @param nextBlock Proposed serialized block.
 * @param baseHash  Base block hash.
 * @param nextHash  Proposed block hash.
 * @param path      Top-level ordinal path.
 * @return Operation body.
 */
function getUpdateOperation(
	baseBlock: string,
	nextBlock: string,
	baseHash: string,
	nextHash: string,
	path: number[]
): Record< string, unknown > {
	const baseBlockName = getBlockRecordName( baseBlock );
	const nextBlockName = getBlockRecordName( nextBlock );

	if ( null !== baseBlockName && baseBlockName === nextBlockName ) {
		const richTextOperation = getRichTextOperation(
			baseBlock,
			nextBlock,
			baseHash,
			nextHash,
			baseBlockName,
			path
		);
		if ( null !== richTextOperation ) {
			return richTextOperation;
		}

		return {
			type: 'block.update_serialized',
			automergePrimitive: 'Automerge.Map.set',
			path,
			blockUid: 'top:' + baseHash,
			blockName: baseBlockName,
			baseBlockHash: baseHash,
			proposedBlockHash: nextHash,
			changeRange: getContentChangeRange( baseBlock, nextBlock ),
			serializedBlock: nextBlock,
		};
	}

	return {
		type: 'block.replace',
		automergePrimitive: 'Automerge.Map.set+Automerge.List.insert',
		path,
		blockUid: 'top:' + nextHash,
		baseBlockHash: baseHash,
		proposedBlockHash: nextHash,
		baseBlockName,
		proposedBlockName: nextBlockName,
		serializedBlock: nextBlock,
	};
}

/**
 * Twin of `wp_de_rtc_have_same_serialized_block_multiset`.
 *
 * @param first  First hash list.
 * @param second Second hash list.
 * @return Whether the multisets match.
 */
function sameHashMultiset( first: string[], second: string[] ): boolean {
	if ( first.length !== second.length ) {
		return false;
	}
	const counts = new Map< string, number >();
	for ( const hash of first ) {
		counts.set( hash, ( counts.get( hash ) ?? 0 ) + 1 );
	}
	for ( const hash of second ) {
		const count = counts.get( hash ) ?? 0;
		if ( 0 === count ) {
			return false;
		}
		counts.set( hash, count - 1 );
	}
	return true;
}

/**
 * Twin of `wp_de_rtc_get_automerge_block_native_operations` (+ the
 * append helper's actor/sequence/id stamping).
 *
 * @param baseRecords Base serialized records.
 * @param nextRecords Proposed serialized records.
 * @param actor       Actor label.
 * @return Block-native operations.
 */
function getBlockNativeOperations(
	baseRecords: string[],
	nextRecords: string[],
	actor: string
): Array< Record< string, unknown > > {
	const operations: Array< Record< string, unknown > > = [];
	const append = ( operation: Record< string, unknown > ) => {
		const sequence = operations.length;
		operations.push( {
			actor,
			sequence,
			id: `${ actor }:${ sequence }`,
			...operation,
		} );
	};

	const baseHashes = baseRecords.map( hashDeRtcContent );
	const nextHashes = nextRecords.map( hashDeRtcContent );

	const recordsEqual =
		baseRecords.length === nextRecords.length &&
		baseRecords.every(
			( record, index ) => record === nextRecords[ index ]
		);

	if (
		baseRecords.length === nextRecords.length &&
		! recordsEqual &&
		sameHashMultiset( baseHashes, nextHashes ) &&
		new Set( baseHashes ).size === baseHashes.length
	) {
		nextRecords.forEach( ( nextRecord, index ) => {
			if ( baseRecords[ index ] === nextRecord ) {
				return;
			}
			const fromIndex = baseHashes.indexOf( nextHashes[ index ] );
			if ( -1 !== fromIndex && fromIndex !== index ) {
				append( {
					type: 'block.move',
					automergePrimitive: 'Automerge.List.move',
					fromPath: [ fromIndex ],
					toPath: [ index ],
					blockUid: 'top:' + nextHashes[ index ],
					blockHash: nextHashes[ index ],
				} );
			}
		} );
		return operations;
	}

	if ( baseRecords.length === nextRecords.length ) {
		baseRecords.forEach( ( baseRecord, index ) => {
			if ( baseRecord === nextRecords[ index ] ) {
				return;
			}
			append(
				getUpdateOperation(
					baseRecord,
					nextRecords[ index ],
					baseHashes[ index ],
					nextHashes[ index ],
					[ index ]
				)
			);
		} );
		return operations;
	}

	let prefix = 0;
	while (
		prefix < baseRecords.length &&
		prefix < nextRecords.length &&
		baseRecords[ prefix ] === nextRecords[ prefix ]
	) {
		prefix++;
	}
	let suffix = 0;
	while (
		suffix < baseRecords.length - prefix &&
		suffix < nextRecords.length - prefix &&
		baseRecords[ baseRecords.length - 1 - suffix ] ===
			nextRecords[ nextRecords.length - 1 - suffix ]
	) {
		suffix++;
	}

	for (
		let index = baseRecords.length - suffix - 1;
		index >= prefix;
		index--
	) {
		append( {
			type: 'block.delete',
			automergePrimitive: 'Automerge.List.delete',
			path: [ index ],
			index,
			blockUid: 'top:' + baseHashes[ index ],
			blockHash: baseHashes[ index ],
		} );
	}

	for ( let index = prefix; index < nextRecords.length - suffix; index++ ) {
		append( {
			type: 'block.insert',
			automergePrimitive: 'Automerge.List.insert',
			path: [ index ],
			index,
			blockUid: 'top:' + nextHashes[ index ],
			blockHash: nextHashes[ index ],
			blockName: getBlockRecordName( nextRecords[ index ] ),
			serializedBlock: nextRecords[ index ],
		} );
	}

	return operations;
}

/* -------------------------------------------------------------------- */
/* The builder.                                                         */
/* -------------------------------------------------------------------- */

/**
 * Twin of `wp_de_rtc_create_automerge_update_for_content_change`: builds
 * the block-native client-update descriptor for a (base, proposed) pair.
 *
 * @param base  Base post content (the canonical content of the
 *              proposal's declared base version, as the server sent it).
 * @param next  Proposed post content.
 * @param actor Actor label for operation ids (not fingerprinted).
 * @return The client update descriptor.
 */
export function buildDeRtcClientUpdate(
	base: string,
	next: string,
	actor: string
): DeRtcClientUpdate {
	base = canonicalizeCoreBlockNames( base );
	next = canonicalizeCoreBlockNames( next );
	const baseRecords = getTopLevelBlockRecords( base );
	const nextRecords = getTopLevelBlockRecords( next );

	if ( null === baseRecords || null === nextRecords ) {
		const changeRange = getContentChangeRange( base, next );
		return {
			format: 'native-automerge-blocks-v1',
			schema: 'de-rtc-automerge-v1',
			operations: [
				{
					type: 'document.replace_unsupported',
					automergePrimitive: 'Automerge.Map.set',
					actor,
					sequence: 0,
					id: `${ actor }:0`,
					baseContentHash: hashDeRtcContent( base ),
					proposedContentHash: hashDeRtcContent( next ),
					changeRange,
				},
			],
			stateVector: { [ actor ]: 1 },
			baseContentHash: hashDeRtcContent( base ),
			proposedContentHash: hashDeRtcContent( next ),
			baseBlockCount: null,
			proposedBlockCount: null,
		};
	}

	const operations = getBlockNativeOperations(
		baseRecords,
		nextRecords,
		actor
	);

	return {
		format: 'native-automerge-blocks-v1',
		schema: 'de-rtc-automerge-v1',
		operations,
		stateVector:
			operations.length > 0 ? { [ actor ]: operations.length } : {},
		baseContentHash: hashDeRtcContent( base ),
		proposedContentHash: hashDeRtcContent( next ),
		baseBlockCount: baseRecords.length,
		proposedBlockCount: nextRecords.length,
	};
}

/**
 * Twin of `wp_de_rtc_get_automerge_block_native_operation_fingerprints`
 * (+ the text-splice fingerprint helper). Exposed for the cross-language
 * vector suite and client-side self-checks; the authoritative comparison
 * happens server-side in PHP.
 *
 * @param operations Block-native operations.
 * @return Comparable fingerprints.
 */
export function fingerprintDeRtcOperations(
	operations: Array< Record< string, unknown > >
): Array< Record< string, unknown > > {
	const toIntArray = ( value: unknown ): number[] | null =>
		Array.isArray( value )
			? value.map( ( entry ) => Math.trunc( Number( entry ) || 0 ) )
			: null;

	return operations.map( ( operation ) => {
		const splice = operation.textSplice as
			| Record< string, unknown >
			| undefined;
		const insertText =
			'string' === typeof splice?.insertText
				? ( splice.insertText as string )
				: '';
		return {
			type: 'string' === typeof operation.type ? operation.type : '',
			path: toIntArray( operation.path ),
			fromPath: toIntArray( operation.fromPath ),
			toPath: toIntArray( operation.toPath ),
			index:
				undefined !== operation.index && null !== operation.index
					? Math.trunc( Number( operation.index ) || 0 )
					: null,
			blockHash:
				'string' === typeof operation.blockHash
					? operation.blockHash
					: null,
			baseBlockHash:
				'string' === typeof operation.baseBlockHash
					? operation.baseBlockHash
					: null,
			proposedBlockHash:
				'string' === typeof operation.proposedBlockHash
					? operation.proposedBlockHash
					: null,
			blockName:
				'string' === typeof operation.blockName
					? operation.blockName
					: null,
			baseBlockName:
				'string' === typeof operation.baseBlockName
					? operation.baseBlockName
					: null,
			proposedBlockName:
				'string' === typeof operation.proposedBlockName
					? operation.proposedBlockName
					: null,
			serializedBlockHash:
				'string' === typeof operation.serializedBlock
					? hashDeRtcContent( operation.serializedBlock )
					: null,
			changedTextIndexes: toIntArray( operation.changedTextIndexes ),
			textSplice: splice
				? {
						changed: Boolean( splice.changed ),
						start: Math.trunc( Number( splice.start ) || 0 ),
						deleteCount: Math.trunc(
							Number( splice.deleteCount ) || 0
						),
						insertTextHash: sha256Hex( insertText ),
						insertCount: Math.trunc(
							Number( splice.insertCount ) || 0
						),
						end: Math.trunc( Number( splice.end ) || 0 ),
						delta: Math.trunc( Number( splice.delta ) || 0 ),
				  }
				: null,
		};
	} );
}
